routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    ProfileController,
    CompanyController,
    ParamController,
    UserController,
    JobController
};
use App\Models\Job;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function ()
{
    Route::get('/dashboard',function (){
        return view('dashboard');
    })->middleware(['verified']);

    Route::resources([
        'users' => UserController::class,
        'drugs' => \App\Http\Controllers\DrugController::class,
        'diseases' => \App\Http\Controllers\DiseasesController::class,
        'procedures' => \App\Http\Controllers\ProcedureController::class,
        'blogs' => \App\Http\Controllers\BlogController::class,
        'specialties' => \App\Http\Controllers\SpecialtyController::class,
        'services' => \App\Http\Controllers\ServiceController::class,
    ]);

//    Route::middleware(['admin'])->group(function ()
//    {
//        Route::resources([
//            'params' => ParamController::class,
//        ]);
//    });

//    Route::get('params/status/{id}', [ParamController::class, "toggleStatus"])->name('params.toggle-status');
//
//    Route::get('job-calender', [JobController::class, 'jobCalender'])->name('jobCalender');
//    Route::get('job-logs', [JobController::class, 'jobLogs'])->name('jobLogs');
//    Route::get('job-assign-member/{id}', [JobController::class, 'jobAssignMember'])->name('jobAssignMember');
//    Route::post('job-assignStore/{id}', [JobController::class, 'jobAssignStore'])->name('jobAssignStore');
//    Route::delete('jobs/images/{id}', [JobController::class, 'imageDelete'])->name('jobs.images');
//    Route::post('airtable-store', [JobController::class, "airtableStore"])->name('airtableStore');
//    Route::get('job-complete', [JobController::class, 'jobComplete'])->name('jobComplete');
//
//
    //Appointments
    Route::get('appointments', [\App\Http\Controllers\UserController::class, 'Appointments'])->name('appointments.index');

    Route::controller(ProfileController::class)->prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'edit')->name('edit');
        Route::patch('/', 'update')->name('update');
        Route::delete('/', 'destroy')->name('destroy');

        Route::view('/change-password', 'profile.change-password')->name('password');
        Route::post('/change-password', 'changePassword')->name('change-password');
    });
});


///front

Route::get('/', [\App\Http\Controllers\Front\HomeController::class, 'index'])->name('home');
Route::get('/page/diseases-condition', [\App\Http\Controllers\Front\HomeController::class, 'diseasesCondition'])->name('diseases_condition');
Route::get('/page/diseases-condition-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'diseasesConditionDetail'])->name('diseasesConditionDetail');

Route::get('/page/drugs', [\App\Http\Controllers\Front\HomeController::class, 'drug'])->name('drug');
Route::get('/page/drug-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'drugDetail'])->name('drugDetail');

Route::get('/page/procedures', [\App\Http\Controllers\Front\HomeController::class, 'procedure'])->name('procedure');
Route::get('/page/procedure-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'procedureDetail'])->name('procedureDetail');

Route::get('/page/doctors', [\App\Http\Controllers\Front\HomeController::class, 'doctor'])->name('doctor');
Route::get('/page/news-feeds', [\App\Http\Controllers\Front\HomeController::class, 'newsfeeds'])->name('newsfeeds');
Route::get('/page/about-us', [\App\Http\Controllers\Front\HomeController::class, 'aboutus'])->name('aboutUs');
Route::get('/page/contact-us', [\App\Http\Controllers\Front\HomeController::class, 'contactus'])->name('contactUs');
Route::post('/page/contactus-store', [\App\Http\Controllers\Front\HomeController::class, 'contactStore'])->name('contactStore');

//news feed detail route
Route::get('/page/news-feed-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'newsFeedDetail'])->name('newsFeedDetail');


Route::get('/request-appointment/{id}', [\App\Http\Controllers\Front\HomeController::class, 'requestAppointment'])->name('requestAppointment');
Route::post('/appointmentStore', [\App\Http\Controllers\Front\HomeController::class, 'appointmentStore'])->name('appointmentStore');

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\TraitLibraries\FcmManager;
use App\TraitLibraries\ModelDependentUpload;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, ModelDependentUpload,SoftDeletes;


    const admin_user = 1;
    const member = 2;

    const type = [
        1 => 'admin',
        2 => 'member',
//        3 => 'nurse',
    ];

    const genders = [
        1 => 'male',
        2 => 'female',
    ];


//    const nurseType = [
//        1 => 'LVN',
//        2 => 'CNA',
//    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'job_category_id',
        'gender',
        'email',
        'phone',
        'password',
        'specialty',
        'type',
        'otp',
        'photo',
        'address',
        'lat',
        'long',
        'document',
        'doc_approved',
        'service_id',
        'state'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function fetch()
    {
        return self::all();
    }

    public function send_message($title, $message, $data = [])
    {
        if ($this->fcm_token)
            FcmManager::send($this, $title, $message, $data);
    }
    public function specialtie(){
        return $this->hasOne(Specialty::class, 'id', 'specialty');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Api\TwilioController;
use App\Http\Controllers\Controller;
use App\Http\Resources\CompanyResource;
use App\Http\Resources\JobResource;
use App\Http\Resources\RatingResource;
use App\Models\Company;
use App\Models\FcmHistory;
use App\Models\Job;
use App\Models\Member;
use App\models\MemberFcmToken;
use App\Models\Params;
use App\Models\Ratings;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Mockery\Exception;

class UserController extends BaseController
{


    protected $mainViewFolder = 'users.';


    /**
     * The user repository instance.
     */
    protected $_user;

    public function __construct(User $user)
    {
        $this->_user = $user;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $users = User::paginate(20);

        return view($this->mainViewFolder . 'index', ['users' => $users]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $model = $this->_user;

        return view($this->mainViewFolder . 'form', compact('model'));
    }


    public function edit($id)
    {
        $model = User::findOrFail($id);
        $model->password = '';

        return view($this->mainViewFolder . 'form', compact('model'));
    }

    public function store(Request $request)
    {
        try {
            $validator = Validator::make($request->all(), [
                'first_name' => 'required',
                'last_name' => 'required',
                'email' => 'required|email|unique:users',
                'phone' => 'required|unique:users',
//                'uid' => 'required|unique:users',
                 'password' => 'required|min:6|confirmed',
                // 'type' => 'required',
            ]);

            if ($validator->fails()) {
                return $this->sendResult('Validation Error.', config('codes.REQUEST_VALIDATAION_ERROR'), $validator->errors()->first(), $request);
            }

            $user = new User($request->all());
            $hashed = Hash::make($request->password);
            $user->password = $hashed;
            $user->type = User::member;

            if (!$user->save()) {
                throw new \Exception('Error saving user');
            }
            $token = $user->createToken("API TOKEN")->plainTextToken;
            return $this->sendResult('User Created Successfully', config('codes.SUCCESS'), ['user' => $user, 'token' => $token], $request);
        } catch (Exception $e) {
            return $this->sendResult('User Error.', config('codes.REQUEST_VALIDATAION_ERROR'), ['data' => $e->getMessage()], $request);
        }
        return back()->withInput($request->all());
    }


    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'type' => 'required',
        ]);
        if ($validator->fails()) {
            return $this->sendError("Validation Error.", $validator->errors());
        }


        try {
            $this->_user = $this->_user->findOrFail($id);

            $this->_user->fill($request->except('password'));

            if ($request->password != null) {
                $this->_user->password = bcrypt($request->password);
            }
            // if the value exist in request filled
            if (!$this->_user->save())
                throw new \Exception('User not updated');

            $request->session()->flash('success', 'User Update successfully');

            return redirect(route('users.index'));

        } catch (\Exception $exception) {
            $request->session()->flash('error', $exception->getMessage());
        }

        return back()->withInput($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        try {

            $this->_user = $this->_user->findOrFail($id);
            if ($this->_user->delete())
                $request->session()->flash('success', 'User deleted successfully');

        } catch (\Exception $e) {
            $request->session()->flash('error', $e->getMessage());
        }
        return back();

    }


    public function deleteAcount(Request $request){
        $member = User::where('id',$request->user()->id)->first();
        $member->delete();
        return $this->sendResult('Account Successfully delete.', config('codes.SUCCESS'), 'Account Successfully delete', $request);
    }




}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Facades\FirebaseService;
use App\Http\Resources\UserResource;
use App\Models\Company;
use App\Models\ContactUs;
use App\Models\JobCategories;
use App\Models\Notifications;
use App\Models\RequestAppointment;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
//use Kreait\Firebase\Contract\Database;
use Kreait\Firebase\Database;
use Kreait\Laravel\Firebase\Facades\Firebase;
use Kreait\Firebase\Factory;
use function Kreait\Firebase\RemoteConfig\equalsTo;

//use Kreait\Firebase\Auth;


class UserController extends Controller
{


    protected $mainViewFolder = 'users.';


    /**
     * The user repository instance.
     */
    protected $_user;

    public function __construct(User $user)
    {
        $this->_user = $user;

    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $users = User::fetch();

        return view($this->mainViewFolder . 'index', ['users' => $users, 'type' => User::type]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $model = $this->_user;
        return view($this->mainViewFolder . 'form', compact('model'));
    }


    public function edit($id)
    {
        $model = User::findOrFail($id);
        $model->password = '';
        return view($this->mainViewFolder . 'form', compact('model'));
    }


//    public function listShow(Request $request)
//    {
//        $users = User::query();
//        $users = $users->orderBy("id",'desc');
//        $users = $users->paginate($request->get('per_page',10));
//        return  $this->sendResponse(UserResource::collection($users),'User data');
//    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'phone' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed',
            'type' => 'required',
//            'job_category_id' => 'required',
        ]);

        try {
            // Start Transaction
            DB::beginTransaction();
            $this->_user = new User($request->except('password', 'password_confirmation'));
            $this->_user->password = bcrypt($request->password);

            if (!$this->_user->save())
                throw new \Exception('Error saving user');

            DB::commit();
            $request->session()->flash('success', 'User store successfully');

            return redirect(route('users.index'));

        } catch (\Exception $exception) {
            DB::rollBack();
            $request->session()->flash('User', $exception->getMessage());
        }
        return back()->withInput($request->all());
    }


    public function update(Request $request, $id)
    {

        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'type' => 'required',
        ]);
        if ($validator->fails()) {
            return $this->sendError("Validation Error.",$validator->errors());
        }


        try {
            $this->_user = $this->_user->findOrFail($id);

            $this->_user->fill($request->except('password'));

            if ($request->password != null) {
                $this->_user->password = bcrypt($request->password);
            }
            // if the value exist in request filled
            if (!$this->_user->save())
                throw new \Exception('User not updated');

            $request->session()->flash('success', 'User Update successfully');

            return redirect(route('users.index'));

        } catch (\Exception $exception) {
            $request->session()->flash('error', $exception->getMessage());
        }

        return back()->withInput($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            $this->_user = $this->_user->findOrFail($id);
            if ($this->_user->delete())
                $request->session()->flash('success', 'User deleted successfully');

        } catch (\Exception $e) {
            $request->session()->flash('error', $e->getMessage());
        }
        return back();

    }

    public function VerifyDocument(int $user_id)
    {
        $user = User::findOrFail($user_id);
        if ($user->document) {
            $user->update(["doc_approved" => 1]);
            return redirect()->route('users.index')->with('success', 'Document Approved');
        }
        return redirect()->route('users.index')->with('warning', 'No Document Found');
    }


    public function Appointments(Request $request)
    {
        $appointments = RequestAppointment::query();
        if(Auth::user()->type != User::admin_user){
            $appointments  = $appointments->where('user_id',Auth::id());
        }
        $appointments  = $appointments->orderBy('id','desc')->paginate($request->get('per_page',10));
        return view($this->mainViewFolder . 'appointments', compact('appointments'));
    }





}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Manage User') }}
{{--            <a href="{{ route('users.create') }}" class="btn btn-primary pull-right button-left">Add New</a>--}}
    </x-slot>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-content">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0" id="usersTable">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Gender</th>
                                    <th>Job Category</th>
                                    <th>Type</th>
{{--                                    <th>Company</th>--}}
{{--                                    <th>Document</th>--}}
{{--                                    <th>Verify</th>--}}
                                    <th>Created At</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{$user->id}}</td>
                                        <td>{{$user->first_name}}</td>
                                        <td>{{$user->last_name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->phone}}</td>
                                        <td>{{\App\Models\User::genders[$user->gender] ?? ''}}</td>
                                        <td>{{$user->jobCategory->title ?? ""}}</td>
                                        <td>{{@$type[$user->type]}}
{{--                                            <span class="text-muted">{{$user->nurse_type ? '(' . strtolower(\App\Models\User::nurseType[$user->nurse_type]) . ')'  : '' }}</span>--}}
                                        </td>
{{--                                        <td>{{$user->company->name ?? '-'}}</td>--}}
{{--                                        <td class="text-nowrap">--}}
{{--                                            @if (!empty($user->document))--}}
{{--                                                    <a class="btn btn-sm btn-outline-info" href="{{$user->document ?? '#'}}" download=""><i class="tf-icons bx bx-sm bx-cloud-download"></i> Download</a>--}}
{{--                                            @else--}}
{{--                                                <span class="text-muted">N/A</span>--}}
{{--                                            @endif--}}
{{--                                        </td>--}}
{{--                                        <td>--}}
{{--                                            @if ($user->doc_approved)--}}
{{--                                                <i class="tf-icons bx bx-sm bx-check-double text-success"></i>--}}
{{--                                            @elseif (empty($user->document))--}}
{{--                                                <i class="tf-icons bx bx-sm bx-x text-danger"></i>--}}
{{--                                            @else--}}
{{--                                                <a class="btn btn-sm btn-primary" href="{{ route('users.verify.doc', $user->id)}}">Verify</a>--}}
{{--                                            @endif--}}
{{--                                        </td>--}}
                                        <td class="text-nowrap" title="{{ $user->created_at }}">{{ date("d M, Y", strtotime($user->created_at)) }}</td>

                                        <td>
{{--                                            <a href="{{ route('users.edit', $user->id)}}"><i class="tf-icons bx bx-edit"></i></a>--}}
{{--                                            <form action="{{ route('users.destroy', $user->id)}}" method="post" id="user_delete">--}}
{{--                                                @csrf--}}
{{--                                                @method('DELETE')--}}
{{--                                                <i class="tf-icons bx bx-trash text-danger listing_delete_icon" form_id="user_delete"></i>--}}

{{--                                            </form>--}}


{{--                                            @if (Auth::user()->type == \App\Models\User::company_user)--}}
{{--                                                <a type="button" class="mb-2 text-info" data-bs-toggle="modal"--}}
{{--                                                   data-bs-target="#exampleModal" data-id="{{ $user->id }}" fid="{{\Illuminate\Support\Facades\Auth::user()->uid}}" toid="{{$user->uid}}" title="send message">--}}
{{--                                                    <i class="tf-icons bx bx-chat"></i>--}}
{{--                                                </a>--}}
{{--                                            @endif--}}
{{--                                            @if (Auth::user()->type == \App\Models\User::admin_user)--}}
{{--                                                <a type="button" class="mb-2 text-info send_notification" data-bs-toggle="modal"--}}
{{--                                                   data-bs-target="#exampleModal1" uid="{{ $user->uid }}" title="send notification">--}}
{{--                                                    <i class="tf-icons bx bx-notification"></i>--}}
{{--                                                </a>--}}
{{--                                            @endif--}}
{{--                                            <a href="{{ route('realTimeChat', ['phone'=>$user->phone]) }}"><i class="tf-icons bx bx-chat"></i></a>--}}
                                            <a href="{{ route('users.edit', $user->id) }}"><i class="tf-icons bx bx-edit"></i></a>
{{--                                            <form action="{{ route('users.destroy', $user->id)}}" method="post" id="company_delete"--}}
{{--                                                  style="display: inline-block">--}}
{{--                                                @csrf--}}
{{--                                                @method('DELETE')--}}
{{--                                                <i class="tf-icons bx bx-trash text-danger listing_delete_icon" form_id="company_delete{{$user->id}}"></i>--}}
{{--                                            </form>--}}

                                            <form style="display: inline" action="{{ route('users.destroy', $user->id)}}"
                                                  id="delete_form_{{$user->id}}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <a class="badge badge-light delete-confirm-id"
                                                   data-id="{{$user->id}}" title="Delete">
                                                    <i class="tf-icons bx bx-trash text-danger listing_delete_icon"></i></a>
                                            </form>

                                        </td>

                                        </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Send Message</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
{{--                    <form method="post">--}}
                        @csrf
                        <div class="mb-3">
{{--                            <label for="assigned_to">Assigned To</label>--}}
                            <input type="text" name="message"  id="message" class="form-control">
                        </div>
                        <button type="submit" id="sent" class="btn btn-primary">Submit</button>
{{--                    </form>--}}
                </div>
            </div>
        </div>
    </div>

{{--    <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">--}}
{{--        <div class="modal-dialog modal-dialog-centered">--}}
{{--            <div class="modal-content">--}}
{{--                <div class="modal-header">--}}
{{--                    <h5 class="modal-title" id="exampleModalLabel1">Send Notification</h5>--}}
{{--                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>--}}
{{--                </div>--}}
{{--                <div class="modal-body">--}}
{{--                <form method="post" action="{{route("sendNotification")}}">--}}
{{--                    @csrf--}}
{{--                    <div class="mb-3">--}}
{{--                        <input type="text" name="message"  id="message" class="form-control">--}}
{{--                        <input type="hidden" name="uid"  id="uid" class="form-control">--}}
{{--                    </div>--}}
{{--                    <button type="submit" id="sent" class="btn btn-primary">Submit</button>--}}
{{--                </form>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}

    <x-slot name="scripts">
    </x-slot>
</x-app-layout>

resources/views/users/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: warispopal
 * Date: 1/12/19
 * Time: 10:04 PM
 */

// user view

?>
<x-app-layout>
    <x-slot name="header">
        {!! $model->name !!}
    </x-slot>
    <div class="row">
        <div class="col-2"></div>
        <!-- Users detail page-->
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">User Details</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>{{$model->id}}</td>
                                    <td>{{$model->name}}</td>
                                    <td>{{$model->email}}</td>
                                    <td>{{$model->created_at}}</td>
                                    <td>{{$model->updated_at}}</td>
                                    <td>
                                        <a href="{{ route('users.edit', $model->id) }}"
                                           class="btn btn-primary">Edit</a>
                                        <form action="{{ route('users.destroy', $model->id)}}" method="post"
                                              style="display: inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('users.index') }}" class="btn btn-primary">Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</x-app-layout>