routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    ProfileController,
    CompanyController,
    ParamController,
    UserController,
    JobController
};
use App\Models\Job;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function ()
{
    Route::get('/dashboard',function (){
        return view('dashboard');
    })->middleware(['verified']);

    Route::resources([
        'users' => UserController::class,
        'drugs' => \App\Http\Controllers\DrugController::class,
        'diseases' => \App\Http\Controllers\DiseasesController::class,
        'procedures' => \App\Http\Controllers\ProcedureController::class,
        'blogs' => \App\Http\Controllers\BlogController::class,
        'specialties' => \App\Http\Controllers\SpecialtyController::class,
        'services' => \App\Http\Controllers\ServiceController::class,
    ]);

//    Route::middleware(['admin'])->group(function ()
//    {
//        Route::resources([
//            'params' => ParamController::class,
//        ]);
//    });

//    Route::get('params/status/{id}', [ParamController::class, "toggleStatus"])->name('params.toggle-status');
//
//    Route::get('job-calender', [JobController::class, 'jobCalender'])->name('jobCalender');
//    Route::get('job-logs', [JobController::class, 'jobLogs'])->name('jobLogs');
//    Route::get('job-assign-member/{id}', [JobController::class, 'jobAssignMember'])->name('jobAssignMember');
//    Route::post('job-assignStore/{id}', [JobController::class, 'jobAssignStore'])->name('jobAssignStore');
//    Route::delete('jobs/images/{id}', [JobController::class, 'imageDelete'])->name('jobs.images');
//    Route::post('airtable-store', [JobController::class, "airtableStore"])->name('airtableStore');
//    Route::get('job-complete', [JobController::class, 'jobComplete'])->name('jobComplete');
//
//
    //Appointments
    Route::get('appointments', [\App\Http\Controllers\UserController::class, 'Appointments'])->name('appointments.index');

    Route::controller(ProfileController::class)->prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'edit')->name('edit');
        Route::patch('/', 'update')->name('update');
        Route::delete('/', 'destroy')->name('destroy');

        Route::view('/change-password', 'profile.change-password')->name('password');
        Route::post('/change-password', 'changePassword')->name('change-password');
    });
});


///front

Route::get('/', [\App\Http\Controllers\Front\HomeController::class, 'index'])->name('home');
Route::get('/page/diseases-condition', [\App\Http\Controllers\Front\HomeController::class, 'diseasesCondition'])->name('diseases_condition');
Route::get('/page/diseases-condition-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'diseasesConditionDetail'])->name('diseasesConditionDetail');

Route::get('/page/drugs', [\App\Http\Controllers\Front\HomeController::class, 'drug'])->name('drug');
Route::get('/page/drug-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'drugDetail'])->name('drugDetail');

Route::get('/page/procedures', [\App\Http\Controllers\Front\HomeController::class, 'procedure'])->name('procedure');
Route::get('/page/procedure-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'procedureDetail'])->name('procedureDetail');

Route::get('/page/doctors', [\App\Http\Controllers\Front\HomeController::class, 'doctor'])->name('doctor');
Route::get('/page/news-feeds', [\App\Http\Controllers\Front\HomeController::class, 'newsfeeds'])->name('newsfeeds');
Route::get('/page/about-us', [\App\Http\Controllers\Front\HomeController::class, 'aboutus'])->name('aboutUs');
Route::get('/page/contact-us', [\App\Http\Controllers\Front\HomeController::class, 'contactus'])->name('contactUs');
Route::post('/page/contactus-store', [\App\Http\Controllers\Front\HomeController::class, 'contactStore'])->name('contactStore');

//news feed detail route
Route::get('/page/news-feed-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'newsFeedDetail'])->name('newsFeedDetail');


Route::get('/request-appointment/{id}', [\App\Http\Controllers\Front\HomeController::class, 'requestAppointment'])->name('requestAppointment');
Route::post('/appointmentStore', [\App\Http\Controllers\Front\HomeController::class, 'appointmentStore'])->name('appointmentStore');

require __DIR__.'/auth.php';

app/Models/Procedure.php
<?php

namespace App\Models;

use App\TraitLibraries\ModelDependentUpload;
use App\TraitLibraries\ModelHelper;
use App\TraitLibraries\ModelSearch;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;

class Procedure extends Model
{
    use HasFactory, ModelHelper, ModelDependentUpload, ModelSearch;
    public static $filepath = "procedures";
    protected $table = 'procedures';

    const types = [
        self::by_drug_name   => 'By Drug Name',
        self::by_therapeutic_classification    => 'By Therapeutic Classification',
    ];

    const by_drug_name    = 0;
    const by_therapeutic_classification     = 1;

    const specialties = [
        "aesthetic_procedures" => 'Aesthetic Procedures',
        "eye_ear_nose_and_throat" => 'Eye, Ear, Nose, and Throat',
        "gastroenterology_procedures" => 'Gastroenterology Procedures',
        "gynecology_and_urology" => 'Gynecology and Urology',
        "injections_soft_tissue_and_joint" => 'Injections - Soft Tissue and Joint',
        "nail_procedures" => 'Nail Procedures',
        "pediatrics" => 'Pediatrics',
        "physical_examination" => 'Physical Examination',
        "skin_surgery" => 'Skin Surgery',
        "splints_and_casts" => 'Splints and Casts',
        "urgent_and_emergency_care" => 'Urgent and Emergency Care',

    ];



    protected $fillable = [
        'title',
        'short_title',
        'short_description',
        'slug',
        'long_description',
        'banner',
        'specialty',
        'description',
        'type',
        'video_link',
    ];

    public function bannerImages()
    {
        return $this->hasMany(File::class, 'objectId', 'id')
            ->where('object','JOBS')->where('type','banner_image');
    }

    /*
    |--------------------------------------------------------------------------
    | Relations
    |--------------------------------------------------------------------------
    */

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'member_id');
    }

    public function specialtie(){
        return $this->hasOne(Specialty::class, 'id', 'specialty');
    }


}

app/Http/Controllers/ProcedureController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\UserResource;
use App\Models\CompleteJob;
use App\Models\Disease;
use App\Models\Drug;
use App\Models\File;
use App\Models\Job;
use App\Models\JobLog;
use App\Models\Procedure;
use App\Models\Specialty;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Http;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;


class ProcedureController extends Controller
{


    protected $mainViewFolder = 'procedure.';


    /**
     * The user repository instance.
     */
    protected $_procedure;

    public function __construct(Procedure $_procedure)
    {
        $this->_procedure = $_procedure;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $procedures = Procedure::orderBy('id', 'DESC')->get();
        return view($this->mainViewFolder . 'index', ['procedures' => $procedures]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = $this->_procedure;
        $specialties = Specialty::get();
        return view($this->mainViewFolder . 'form', compact('model','specialties'));
    }


    public function edit($id)
    {
        $model = Procedure::findOrFail($id);
        $specialties = Specialty::get();
        return view($this->mainViewFolder . 'form', compact('model','specialties'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title'=>"required",
            'specialty'=>"required",
        ]);

        try {
            // Start Transaction
            $data = $request->all();
            DB::beginTransaction();
            $this->_procedure = new Procedure($data);
            $firstLetter = substr($request->title, 0, 1);
            $this->_procedure->short_title = $firstLetter;
            $this->_procedure->slug = Str::slug($request->title);

            if ($request->hasFile('banner')) {
                $banner = (new Procedure())->modelFileUpload($request->file('banner'));
                $this->_procedure->banner = Procedure::$filepath.'/'.$banner;
            }
            if(!empty($request->file('video_link'))){
                $file = (new Procedure())->modelFileUpload($request->file('video_link'));
                $this->_procedure->video_link = Procedure::$filepath.'/'.$file;
            }

            if (!$this->_procedure->save())
                throw new \Exception('Error saving Procedure');


            DB::commit();
            $request->session()->flash('success', 'Procedure store successfully');

            return redirect(route('procedures.index'));

        } catch (\Exception $exception) {
            DB::rollBack();
            $request->session()->flash('Procedure', $exception->getMessage());
        }
        return back()->withInput($request->all());
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title'=>"required",
            'specialty'=>"required",
        ]);

        try {

            // Start Transaction
            DB::beginTransaction();

            $this->_procedure = $this->_procedure->findOrFail($id);
            $this->_procedure->title = $request->title;
            $this->_procedure->short_title = $request->short_title;
            $this->_procedure->specialties = $request->specialties;
            $this->_procedure->short_description = $request->short_description;
            $firstLetter = substr($request->title, 0, 1);
            $this->_procedure->short_title = $firstLetter;
            $this->_procedure->slug = Str::slug($request->title);

            if ($request->hasFile('banner')) {
                $banner = $this->_procedure->modelFileUpload($request->file('banner'));
                $this->_procedure->banner = Drug::$filepath.'/'.$banner;
            }

            if(!empty($request->file('video_link'))){
                $file = (new Procedure())->modelFileUpload($request->file('video_link'));
                $this->_procedure->video_link = Procedure::$filepath.'/'.$file;
            }

            if (!$this->_procedure->save())
                throw new \Exception('Error saving Procedure');

            DB::commit();
            $request->session()->flash('success', 'Procedure update successfully');

            return redirect(route('procedures.index'));

        } catch (\Exception $exception) {
            DB::rollBack();
            $request->session()->flash('procedure', $exception->getMessage());
        }

        return back()->withInput($request->all());
    }

    public function show(Request $request,$id){
    }

    public function destroy(Request $request, $id)
    {
        try {

            $this->_procedure = $this->_procedure->findOrFail($id);
            if ($this->_procedure->delete())
                $request->session()->flash('success', 'Procedure deleted successfully');

        } catch (\Exception $e) {
            $request->session()->flash('error', $e->getMessage());
        }
        return back();

    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/procedure/_search.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: warispopal
 * Date: 2/2/19
 * Time: 4:47 PM
 */

?>


    <form class="form validate-form" method="GET" novalidate>
        <div class="form-body">
            <h4 class="form-section"><i class=""></i>Search:</h4>
            <div class="row">
                <div class="col-lg-4 col-md-8">
                    <div class="form-group">
                        <label for="basicInputFile">User Name</label>
                        <div class="position-relative has-icon-left">
                            <input type="text" class="form-control"
                                   name="name"
                                   placeholder="Name"
                                   value="{{ request('name') }}">

                            <div class="form-control-position">
                                <i class="ft-user-check info"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="form-group">
                        <label for="basicInputFile">User Email</label>
                        <div class="position-relative has-icon-left">
                            <input type="text" class="form-control"
                                   name="email"
                                   placeholder="Email Address"
                                   value="{{ request('email') }}">
                            <div class="form-control-position">
                                <i class="ft-mail info"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-8">
                    <fieldset class="form-group">
                        <label for="basicSelect">Alpha Roles</label>
                        <select class="form-control" name="alphaRole">
                            <option value="">Select</option>
                            @foreach($alphaRoles as $key => $title)
                                <option value="{{$key}}" {{ ($key == request('alphaRole'))?'selected=""':'' }}>{{$title}}</option>
                            @endForeach
                        </select>
                    </fieldset>
                </div>
                <div class="col-lg-4 col-md-8">
                    <div class="form-group">
                        <label for="basicInputFile">Created</label>
                        <div class="position-relative has-icon-left " id="defaultrange">
                            <input type="text" class="form-control"
                                   name="created_at"
                                   placeholder="Created Date Range"
                                   value="{{ request('created_at') }}">

                            <div class="form-control-position">
                                <i class="ft-clock info"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions right">

            <a href="{{ route('users.index') }}"
               class="btn btn-raised btn-outline-secondary round btn-min-width mr-1 mb-1">Reset</a>
            <button type="submit"
                    class="btn btn-raised btn-outline-success round btn-min-width mr-1 mb-1">
                <i class="fa fa-check-square-o"></i> Search
            </button>
        </div>
    </form>

resources/views/procedure/form.blade.php
<x-app-layout>
    <x-slot name="header">
        {{  $model->exists ? __('Edit Procedure') : __('Create Procedure')  }}

    </x-slot>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" class="form" enctype="multipart/form-data"
                          action="{{ ($model->exists)? route('procedures.update', [$model->id]): route('procedures.store') }}">
                        @if ($model->exists)
                            @method('PUT')
                        @endif
                        @csrf

                        <div class="col-12">
                            <h6 class="fw-semibold">
                                {{  $model->exists ? __('Edit Procedures') : __('Create Procedures')  }}
                            </h6>
                            <hr class="mt-0">
                        </div>

                        <div class="row">
                            <div class="col-4">
                                <div class="fv-plugins-icon-container">
                                    <label class="form-label" for="title">Title</label>
                                    <input type="text" id="title"
                                           value="{!! old('title')??$model->title !!}"
                                           class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}"
                                           placeholder="title"
                                           name="title">
                                    @if ($errors->has('title'))
                                        <div class="fv-plugins-message-container invalid-feedback">
                                            <div data-field="formValidationBio"
                                                 data-validator="stringLength">{{ $errors->first('title') }}</div>
                                        </div>
                                    @endif
                                </div>
                            </div>
{{--                            <div class="col-4">--}}
{{--                                <div class="form-group">--}}
{{--                                    <label for="type">Types</label>--}}
{{--                                    <select id="type" name="type"--}}
{{--                                            class="form-control">--}}
{{--                                        <option value="">Select Type</option>--}}

{{--                                        @foreach(\App\Models\Drug::types as $key =>  $status)--}}
{{--                                            <option value="{{$key}}" {{ (old('type') == $key) ? 'selected=""':'' }} {{ ($model->type == $key) ? 'selected=""':''}} >--}}
{{--                                                {{$status}}</option>--}}
{{--                                        @endForeach--}}
{{--                                    </select>--}}

{{--                                    @if ($errors->has('type'))--}}
{{--                                        <div class="help-block">--}}
{{--                                                    <span class="" role="alert">--}}
{{--                                                                <strong class="text-danger">{{ $errors->first('type') }}</strong>--}}
{{--                                                    </span></div>--}}
{{--                                    @endif--}}
{{--                                </div>--}}
{{--                            </div>--}}
                            <div class="col-4">
                                <div class="form-group">
                                    <label for="specialty">Specialties</label>
                                    <select id="specialty" name="specialty"
                                            class="form-control">
                                        <option value="">Select Specialties</option>

                                        @foreach($specialties as $key =>  $data)
                                            <option value="{{$data->id}}" {{ (old('specialty') == $data->id) ? 'selected=""':'' }} {{ ($model->specialty == $data->id) ? 'selected=""':''}} >
                                                {{$data->name}}</option>
                                        @endForeach
                                    </select>

                                    @if ($errors->has('specialty'))
                                        <div class="help-block">
                                        <span class="" role="alert">
                                                    <strong class="text-danger">{{ $errors->first('specialty') }}</strong>
                                        </span></div>
                                    @endif

                                </div>
                            </div>
                        </div>
                        <div class="row">
{{--                            <div class="col-3">--}}
{{--                                <div class="fv-plugins-icon-container mb-2">--}}
{{--                                    <label class="form-label" for="banner">Banner</label>--}}
{{--                                    <input type="file" id="banner" class="form-control" value="{!! old('banner')??$model->banner !!}"--}}
{{--                                           placeholder="banner" name="banner">--}}
{{--                                    @if ($errors->has('banner'))--}}
{{--                                        <div class="fv-plugins-message-container text-danger">--}}
{{--                                            {{ $errors->first('banner') }}--}}
{{--                                        </div>--}}
{{--                                    @endif--}}
{{--                                </div>--}}
{{--                            </div>--}}
                            <div class="col-3">
                                <div class="fv-plugins-icon-container mb-2">
                                    <label class="form-label" for="video_link">Video</label>
                                    <input type="file" id="video_link" class="form-control"
                                           placeholder="video_link" name="video_link">
                                    @if ($errors->has('video_link'))
                                        <div class="fv-plugins-message-container text-danger">
                                            {{ $errors->first('video_link') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="short_description">Short Description</label>
                                    <textarea type="text"
                                              class="form-control{{ $errors->has('short_description') ? ' is-invalid' : '' }}"
                                              placeholder="short_description"
                                              name="short_description">{{ (old('short_description'))? old('short_description'): $model->short_description }}</textarea>
                                    @if ($errors->has('short_description'))
                                        <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('short_description') }}</strong>
                                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group">
                                <label for="contract_detail">Long Description</label>
                                <textarea type="text" id="long_description"
                                          class="form-control{{ $errors->has('long_description') ? ' is-invalid' : '' }}"
                                          placeholder="Long Description"
                                          name="long_description">{{ (old('long_description '))? old('long_description '): $model->long_description }}</textarea>
                                @if ($errors->has('long_description'))
                                    <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('long_description') }}</strong>
                                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>


    <x-slot name="scripts">
        {{--        <script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_API_KEY') }}&libraries=places&callback=initialize" async defer></script>--}}
        {{--        <script src="{{ asset('assets/js/mapInput.js')}}"></script>--}}
    </x-slot>

</x-app-layout>
<script src="https://cdn.ckeditor.com/4.19.0/standard-all/ckeditor.js"></script>
<script>
    $(document).ready(function() {
        CKEDITOR.replace('long_description', {
            {{--            filebrowserUploadUrl: "{{route('article.upload', ['_token' => csrf_token() ])}}",--}}
            filebrowserUploadMethod: 'form',
            fullPage: false,
            extraPlugins: 'docprops',
            // Disable content filtering because if you use full page mode, you probably
            // want to  freely enter any HTML content in source mode without any limitations.
            allowedContent: true,
            height: 320,
            removeButtons: 'PasteFromWord',

        });
    });
</script>

resources/views/procedure/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: warispopal
 * Date: 1/12/19
 * Time: 10:04 PM
 */

// user view

?>
<x-app-layout>
    <x-slot name="header">
        {!! $model->name !!}
    </x-slot>
    <div class="row">
        <div class="col-2"></div>
        <!-- Users detail page-->
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">User Details</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>{{$model->id}}</td>
                                    <td>{{$model->name}}</td>
                                    <td>{{$model->email}}</td>
                                    <td>{{$model->created_at}}</td>
                                    <td>{{$model->updated_at}}</td>
                                    <td>
                                        <a href="{{ route('users.edit', $model->id) }}"
                                           class="btn btn-primary">Edit</a>
                                        <form action="{{ route('users.destroy', $model->id)}}" method="post"
                                              style="display: inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('users.index') }}" class="btn btn-primary">Back</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</x-app-layout>