routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    ProfileController,
    CompanyController,
    ParamController,
    UserController,
    JobController
};
use App\Models\Job;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function ()
{
    Route::get('/dashboard',function (){
        return view('dashboard');
    })->middleware(['verified']);

    Route::resources([
        'users' => UserController::class,
        'drugs' => \App\Http\Controllers\DrugController::class,
        'diseases' => \App\Http\Controllers\DiseasesController::class,
        'procedures' => \App\Http\Controllers\ProcedureController::class,
        'blogs' => \App\Http\Controllers\BlogController::class,
        'specialties' => \App\Http\Controllers\SpecialtyController::class,
        'services' => \App\Http\Controllers\ServiceController::class,
    ]);

//    Route::middleware(['admin'])->group(function ()
//    {
//        Route::resources([
//            'params' => ParamController::class,
//        ]);
//    });

//    Route::get('params/status/{id}', [ParamController::class, "toggleStatus"])->name('params.toggle-status');
//
//    Route::get('job-calender', [JobController::class, 'jobCalender'])->name('jobCalender');
//    Route::get('job-logs', [JobController::class, 'jobLogs'])->name('jobLogs');
//    Route::get('job-assign-member/{id}', [JobController::class, 'jobAssignMember'])->name('jobAssignMember');
//    Route::post('job-assignStore/{id}', [JobController::class, 'jobAssignStore'])->name('jobAssignStore');
//    Route::delete('jobs/images/{id}', [JobController::class, 'imageDelete'])->name('jobs.images');
//    Route::post('airtable-store', [JobController::class, "airtableStore"])->name('airtableStore');
//    Route::get('job-complete', [JobController::class, 'jobComplete'])->name('jobComplete');
//
//
    //Appointments
    Route::get('appointments', [\App\Http\Controllers\UserController::class, 'Appointments'])->name('appointments.index');

    Route::controller(ProfileController::class)->prefix('profile')->name('profile.')->group(function () {
        Route::get('/', 'edit')->name('edit');
        Route::patch('/', 'update')->name('update');
        Route::delete('/', 'destroy')->name('destroy');

        Route::view('/change-password', 'profile.change-password')->name('password');
        Route::post('/change-password', 'changePassword')->name('change-password');
    });
});


///front

Route::get('/', [\App\Http\Controllers\Front\HomeController::class, 'index'])->name('home');
Route::get('/page/diseases-condition', [\App\Http\Controllers\Front\HomeController::class, 'diseasesCondition'])->name('diseases_condition');
Route::get('/page/diseases-condition-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'diseasesConditionDetail'])->name('diseasesConditionDetail');

Route::get('/page/drugs', [\App\Http\Controllers\Front\HomeController::class, 'drug'])->name('drug');
Route::get('/page/drug-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'drugDetail'])->name('drugDetail');

Route::get('/page/procedures', [\App\Http\Controllers\Front\HomeController::class, 'procedure'])->name('procedure');
Route::get('/page/procedure-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'procedureDetail'])->name('procedureDetail');

Route::get('/page/doctors', [\App\Http\Controllers\Front\HomeController::class, 'doctor'])->name('doctor');
Route::get('/page/news-feeds', [\App\Http\Controllers\Front\HomeController::class, 'newsfeeds'])->name('newsfeeds');
Route::get('/page/about-us', [\App\Http\Controllers\Front\HomeController::class, 'aboutus'])->name('aboutUs');
Route::get('/page/contact-us', [\App\Http\Controllers\Front\HomeController::class, 'contactus'])->name('contactUs');
Route::post('/page/contactus-store', [\App\Http\Controllers\Front\HomeController::class, 'contactStore'])->name('contactStore');

//news feed detail route
Route::get('/page/news-feed-detail/{slug}', [\App\Http\Controllers\Front\HomeController::class, 'newsFeedDetail'])->name('newsFeedDetail');


Route::get('/request-appointment/{id}', [\App\Http\Controllers\Front\HomeController::class, 'requestAppointment'])->name('requestAppointment');
Route::post('/appointmentStore', [\App\Http\Controllers\Front\HomeController::class, 'appointmentStore'])->name('appointmentStore');

require __DIR__.'/auth.php';

resources/views/layouts/_header.blade.php
<nav
    class="layout-navbar container-fluid navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
    id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <!-- Search -->
        <div class="navbar-nav align-items-center">
            <div class="nav-item d-flex align-items-center">
                @if (isset($header))
                    <h4 class="m-auto">{{ $header }}
                @endif
            </div>
        </div>
        <!-- /Search -->

        <ul class="navbar-nav flex-row align-items-center ms-auto">
            <!-- Place this tag where you want the button to render. -->
            <li class="nav-item lh-1 me-3">

                            <span
                                class="github-button">Hello {!! \Illuminate\Support\Facades\Auth::user()->name !!}</span>
            </li>

            <li class="nav-item dropdown-notifications navbar-dropdown dropdown me-3 me-xl-1">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
{{--                    <i class="bx bx-bell bx-sm"></i>--}}
                    <span class="badge bg-danger rounded-pill badge-notifications" id="notificationCount"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-end py-0">
                    <li class="dropdown-menu-header border-bottom">
                        <div class="dropdown-header d-flex align-items-center py-3">
                            <h5 class="text-body mb-0 me-auto">Notification</h5>
                            <a href="#" class="dropdown-notifications-all text-body" data-bs-toggle="tooltip" data-bs-placement="top" aria-label="Mark all as read" data-bs-original-title="Mark all as read"><i class="bx fs-4 bx-envelope-open"></i></a>
                        </div>
                    </li>
                    <li class="dropdown-notifications-list scrollable-container ps">
                        <ul class="list-group list-group-flush" id="notificationNew">

                       </ul>
                        <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></li>
                    <li class="dropdown-menu-footer border-top">
                        <a href="#" class="dropdown-item d-flex justify-content-center p-3">
                            View all notifications
                        </a>
                    </li>
                </ul>
            </li>


            <li class="nav-item lh-1 me-3">

                <form method="POST" action="{{ route('logout') }}">
                    @csrf
                    <x-responsive-nav-link :href="route('logout')"
                                           onclick="event.preventDefault();
                                                                                this.closest('form').submit();">
                        <i class="bx bx-power-off"></i>
                    </x-responsive-nav-link>
                </form>
            </li>

            <!-- User -->
        {{--            <li class="nav-item navbar-dropdown dropdown-user dropdown">--}}
        {{--                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);"--}}
        {{--                   data-bs-toggle="dropdown">--}}
        {{--                    <div class="avatar avatar-online">--}}
        {{--                        <img src="../assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle"/>--}}
        {{--                    </div>--}}
        {{--                </a>--}}
        {{--                <ul class="dropdown-menu dropdown-menu-end">--}}
        {{--                    <li>--}}
        {{--                        <a class="dropdown-item" href="#">--}}
        {{--                            <div class="d-flex">--}}
        {{--                                <div class="flex-shrink-0 me-3">--}}
        {{--                                    <div class="avatar avatar-online">--}}
        {{--                                        <img src="../assets/img/avatars/1.png" alt--}}
        {{--                                             class="w-px-40 h-auto rounded-circle"/>--}}
        {{--                                    </div>--}}
        {{--                                </div>--}}
        {{--                                <div class="flex-grow-1">--}}
        {{--                                    <span class="fw-semibold d-block">John Doe</span>--}}
        {{--                                    <small class="text-muted">Admin</small>--}}
        {{--                                </div>--}}
        {{--                            </div>--}}
        {{--                        </a>--}}
        {{--                    </li>--}}
        {{--                    <li>--}}
        {{--                        <div class="dropdown-divider"></div>--}}
        {{--                    </li>--}}
        {{--                    <li>--}}
        {{--                        <a class="dropdown-item" href="#">--}}
        {{--                            <i class="bx bx-user me-2"></i>--}}
        {{--                            <span class="align-middle">My Profile</span>--}}
        {{--                        </a>--}}
        {{--                    </li>--}}
        {{--                    <li>--}}
        {{--                        <a class="dropdown-item" href="#">--}}
        {{--                            <i class="bx bx-cog me-2"></i>--}}
        {{--                            <span class="align-middle">Settings</span>--}}
        {{--                        </a>--}}
        {{--                    </li>--}}
        {{--                    <li>--}}
        {{--                        <a class="dropdown-item" href="#">--}}
        {{--                        <span class="d-flex align-items-center align-middle">--}}
        {{--                          <i class="flex-shrink-0 bx bx-credit-card me-2"></i>--}}
        {{--                          <span class="flex-grow-1 align-middle">Billing</span>--}}
        {{--                          <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>--}}
        {{--                        </span>--}}
        {{--                        </a>--}}
        {{--                    </li>--}}
        {{--                    <li>--}}
        {{--                        <div class="dropdown-divider"></div>--}}
        {{--                    </li>--}}
        {{--                    <li>--}}


        {{--                            <form method="POST" action="{{ route('logout') }}">--}}
        {{--                                @csrf--}}
        {{--                                <x-responsive-nav-link :href="route('logout')"--}}
        {{--                                                       onclick="event.preventDefault();--}}
        {{--                                                                                this.closest('form').submit();">--}}
        {{--                                    <span class="align-middle">Log Out</span>--}}
        {{--                                </x-responsive-nav-link>--}}
        {{--                            </form>--}}
        {{--                    </li>--}}
        {{--                </ul>--}}
        {{--            </li>--}}
        <!--/ User -->
        </ul>
    </div>
</nav>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        {{--$(document).ready(function() {--}}
        {{--    setInterval(function() {--}}
        {{--        $.ajax({--}}
        {{--            url: "{{route("getNotification")}}",--}}
        {{--            type: "GET",--}}
        {{--            success: function(data) {--}}
        {{--                $("#notificationCount").text(data['count']);--}}
        {{--                $("#notificationCount2").text(data['count']);--}}

        {{--                $('#notificationNew').empty();--}}
        {{--                for (var i = 0; i < data['data'].length; i++) {--}}
        {{--                    var minus = data['data'][i]['diff']+' minus .....';--}}
        {{--                    var title =  data['data'][i]['title'];--}}
        {{--                    var body =  data['data'][i]['body'];--}}
        {{--                    var type =  data['data'][i]['type'];--}}
        {{--                    var uid =  data['data'][i]['id'];--}}
        {{--                    var url = "{{url('/real-time-chat')}}?phone=" + encodeURIComponent(data['data'][i]['phone']);--}}
        {{--                    var fullUrl = "";--}}
        {{--                    if(type == 0){--}}
        {{--                        fullUrl ="<a href='"+ url +"' class='dropdown-notifications-read'>"+"<span class='badge badge-dot'>"+'view'+"</span>"+"</a>";--}}
        {{--                    }--}}

        {{--                    var html = "<li class='list-group-item list-group-item-action dropdown-notifications-item marked-as-read'>"+--}}
        {{--                        "<div class='d-flex'>"+--}}
        {{--                            "<div class='flex-shrink-0 me-3'>"+--}}
        {{--                                "<div class='avatar'>"+--}}
        {{--                                    "<h6 class='w-px-40 h-auto rounded-circle'>"+'✉️'+"</h6>"+--}}
        {{--                                "</div>"+--}}
        {{--                            "</div>"+--}}
        {{--                            "<div class='flex-grow-1'>"+--}}
        {{--                                "<h6 class='mb-1'>"+title+"</h6>"+--}}
        {{--                                "<p class='mb-0'>"+body+"</p>"+--}}
        {{--                                "<small class='text-muted'>"+minus+"</small>"+--}}
        {{--                            "</div>"+--}}
        {{--                            "<div class='flex-shrink-0 dropdown-notifications-actions'>"+--}}
        {{--                                fullUrl--}}
        {{--                            "</div>"+--}}
        {{--                        "</div>"+--}}
        {{--                    "</li>"--}}

        {{--                    $('#notificationNew').append(html);--}}
        {{--                }--}}

        {{--            }--}}
        {{--        });--}}
        {{--    }, 1000); // 1000 ms = 1 second--}}
        {{--});--}}


    </script>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Subber') }}</title>
    <link rel="icon" type="image/x-icon" href="{{asset('front_assets/img/favicon.png')}}">
    <script src="https://cdn.ckeditor.com/4.19.0/standard-all/ckeditor.js"></script>
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

    <!-- Scripts -->
    {{--    @vite(['resources/css/app.css', 'resources/js/app.js'])--}}
{{--    <script src="https://cdn.ckeditor.com/ckeditor5/10.0.1/classic/ckeditor.js"></script>--}}


    <link
        href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet">
    {{--    />--}}

<!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{!! asset('assets/vendor/fonts/boxicons.css') !!}"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">

    <!-- Core CSS -->
    <link rel="stylesheet" href="{!! asset('assets/vendor/css/core.css') !!}" class="template-customizer-core-css"/>
    <link rel="stylesheet" href="{!! asset('assets/vendor/css/theme-default.css') !!}"
          class="template-customizer-theme-css"/>
    <link rel="stylesheet" href="{!! asset('assets/css/demo.css') !!}"/>
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{!! asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css') !!}"/>

    {{--    <link rel="stylesheet" href="{!! asset('assets/vendor/libs/apex-charts/apex-charts.css') !!}"/>--}}

    <link href="{{ asset('assets/vendor/js/select2/css/select2.min.css') }}" rel="stylesheet"/>

    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jqc-1.12.4/dt-1.12.1/b-2.2.3/sl-1.4.0/datatables.min.css"/> -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap4.min.css"/>

    <!-- Helpers -->
    {{--    <script src="{!! asset('assets/vendor/js/helpers.js') !!}"></script>--}}

    {{--    <script src="{!! asset('assets/js/config.js') !!}"></script>--}}
{{--    <link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.10.0/main.min.css" rel="stylesheet">--}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<body>
<!-- Layout wrapper -->
<div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
        <!-- Menu -->

    @include('layouts.navigation')
    <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
            <!-- Navbar -->
            @include('layouts._header')
        <!-- / Navbar -->
            <!-- Content wrapper -->
            <div class="content-wrapper">
                <!-- Content -->

                <div class="container-fluid flex-grow-1 container-p-y">

                    @if(session()->has('success'))
                        <div class="row">
                            <div class="d-flex align-items-center justify-content-center">
                                <div class="col-md-12 p-2 m-2 my-auto justify-content-center">
                                    <div class="alert alert-success alert-dismissible" role="alert">
                                        {!! session()->get('success') !!}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endif
                    @if(session()->has('error'))
                        <div class="row">
                            <div class="d-flex align-items-center justify-content-center">
                                <div class="col-md-12 p-2 m-2 my-auto justify-content-center">
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        {!! session()->get('error') !!}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endif

                    {{ $slot }}
                </div>
                <!-- / Content -->


                <div class="content-backdrop fade"></div>
            </div>
            <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
</div>
<!-- / Layout wrapper -->

<!-- Core JS -->
<!-- build:js assets/vendor/js/core.js -->
<script src="{!! asset('assets/vendor/libs/jquery/jquery.js')!!}"></script>
<script src="{!! asset('assets/vendor/libs/popper/popper.js')!!}"></script>
<script src="{!! asset('assets/vendor/js/bootstrap.js')!!}"></script>
<script src="{!! asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js')!!}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jqc-1.12.4/dt-1.12.1/b-2.2.3/sl-1.4.0/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('assets/vendor/js/select2/select2.min.js') }}"></script>
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>--}}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>


@if (isset($scripts))
    {{ $scripts }}
@endif
<script>
    $('.delete-confirm-id').on('click', function () {
        var id = $(this).attr('data-id');
        console.log(id)
        if (id != undefined) {
            swal.fire({
                title       : 'Are you sure?',
                text        : "You won't be able to revert this!",
                type        : 'warning',
                showCancelButton    : true,
                confirmButtonColor  : '#0CC27E',
                cancelButtonColor   : '#FF586B',
                confirmButtonText   : 'Yes!',
                cancelButtonText    : "No, cancel"
            }).then(function (isConfirm) {
                if (isConfirm.value) {
                    document.getElementById('delete_form_' + id).submit();
                }
            }).catch(swal.noop);
        }
    });



    $(".listing_delete_icon").click(function(){
        var form_id = $(this).attr('form_id');
        $('#'+form_id).submit()
    });

    $(".ajax-view-modal").click(function (e) {

        // e.defaultPrevented;
        let id = $(this).attr("data-modal-id");
        let url = $(this).attr("data-url");
        let object = $("#" + id);

        if (object.length) {
            object.remove();
            object.modal("show");
            return;
        }
        $.ajax({
            url: url,
            type: "GET",
            dataType: "html",
            success: function (html) {
                $(html).appendTo('body');
            },
            error: function (request, status, error) {
                $(request.responseText).appendTo('body');
                $("#" + id).modal("show");

            }, complete: function () {
                $("#" + id).modal("show");
                $('#mySelect2').select2({
                    dropdownParent: $("#" + id),
                    width: '100%'

                });
            }
        });
    });

    $(function () {


        $('body').tooltip({
            selector: '[data-bs-toggle=tooltip]'
        });

        $('.table-responsive').on('show.bs.dropdown', function () {
            $('.table-responsive').css( "overflow", "inherit" );
        });

        $('.table-responsive').on('hide.bs.dropdown', function () {
            $('.table-responsive').css( "overflow", "auto" );
        })
    });


</script>


</body>
</html>

resources/views/layouts/navigation.blade.php
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="my-4">
        <a href="/">
                <img class="img-fluid d-block mx-auto" src="{{asset("front_assets/img/site-identify/logo.png")}}" alt="" width="50%">
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item {{request()->is('/')  ? 'active' : ''}}">
            <a href="{{url('/dashboard')}}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
            </a>
        </li>

        @if (Auth::user()->type == \App\Models\User::admin_user)
            <li class="menu-item {{request()->segment(1) == 'users'  ? 'active' : ''}}">
                <a href="{{route("users.index")}}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-group"></i>
                    <div data-i18n="create">Users</div>
                </a>
            </li>
            <li class="menu-item {{request()->segment(1) == 'blogs'  ? 'active' : ''}}">
                <a href="{{route("blogs.index")}}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-briefcase"></i>
                    <div data-i18n="create">Blogs</div>
                </a>
            </li>
            <li class="menu-item {{request()->segment(1) == 'procedures'  ? 'active' : ''}}">
                <a href="{{route("procedures.index")}}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-briefcase"></i>
                    <div data-i18n="create">Procedures</div>
                </a>
            </li>
            <li class="menu-item {{request()->segment(1) == 'drugs'  ? 'active' : ''}}">
                <a href="{{route("drugs.index")}}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-briefcase"></i>
                    <div data-i18n="create">Drugs</div>
                </a>
            </li>
            <li class="menu-item {{request()->segment(1) == 'diseases'  ? 'active' : ''}}">
                <a href="{{route("diseases.index")}}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-briefcase"></i>
                    <div data-i18n="create">Diseases & Condition</div>
                </a>
            </li>

            <li class="menu-item {{request()->segment(1) == 'specialties'  ? 'active' : ''}}">
                <a href="{{route("specialties.index")}}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-briefcase"></i>
                    <div data-i18n="create">Specialties</div>
                </a>
            </li>

            <li class="menu-item {{request()->segment(1) == 'services'  ? 'active' : ''}}">
                <a href="{{route("services.index")}}" class="menu-link">
                    <i class="menu-icon tf-icons bx bx-briefcase"></i>
                    <div data-i18n="create">Services</div>
                </a>
            </li>

        @endif
        <li class="menu-item {{request()->segment(1) == 'services'  ? 'active' : ''}}">
            <a href="{{route("services.index")}}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-briefcase"></i>
                <div data-i18n="create">Services</div>
            </a>
        </li>
        <li class="menu-item {{request()->segment(1) == 'Appointments'  ? 'active' : ''}}">
            <a href="{{route("appointments.index")}}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-briefcase"></i>
                <div data-i18n="create">Appointments</div>
            </a>
        </li>
        {{--        <li class="menu-item {{request()->segment(1) == 'job-logs'  ? 'active' : ''}}">--}}
{{--            <a href="{{route("jobLogs")}}" class="menu-link">--}}
{{--                <i class="menu-icon tf-icons bx bx-briefcase"></i>--}}
{{--                <div data-i18n="create">JobLogs</div>--}}
{{--            </a>--}}
{{--        </li>--}}


        <li class="menu-item {{request()->segment(1) == 'profile'  ? 'active' : ''}}">
            <a href="{{route("profile.edit")}}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-user"></i>
                <div data-i18n="create">Profile</div>
            </a>
        </li>
{{--        @if (Auth::user()->type == \App\Models\User::admin_user)--}}
{{--            <li class="menu-item {{request()->segment(1) == 'params'  ? 'active' : ''}}">--}}
{{--                <a href="{{route("params.index")}}" class="menu-link">--}}
{{--                    <i class="menu-icon tf-icons bx bx-slider"></i>--}}
{{--                    <div data-i18n="create">Params</div>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--        @endif--}}

{{--        @if (Auth::user()->type == \App\Models\User::company_user)--}}
{{--            <li class="menu-item {{request()->segment(1) == 'messages'  ? 'active' : ''}}">--}}
{{--                <a href="{{route("realTimeChat")}}" class="menu-link">--}}
{{--                    <i class="menu-icon tf-me bx-message"></i>--}}
{{--                    <div data-i18n="create">Messages</div>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--        @endif--}}

    </ul>
</aside>